# Generated by Django 5.2.11 on 2026-02-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevasAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
