# Generated by Django 5.2.11 on 2026-02-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevasAPP', '0002_alter_testimonial_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbanner',
            name='popup_offer_image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
