# Generated by Django 5.2.11 on 2026-03-04 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevasAPP', '0009_zone_remove_product_description_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='express_delivery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='replacement_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tracking_available',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DevasAPP.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DevasAPP.subcategory'),
        ),
    ]
