# Generated by Django 5.2.11 on 2026-03-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevasAPP', '0010_remove_product_express_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
