# Generated by Django 5.2.11 on 2026-03-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevasAPP', '0018_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('order_id', models.CharField(max_length=50)),
                ('reason', models.CharField(choices=[('damaged_during_transit', 'Damaged during transit'), ('incorrect_plant_received', 'Incorrect plant received'), ('severe_wilting_health_issues', 'Severe wilting / Health issues'), ('other', 'Other')], max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='replacement_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
